---
 - name: Install and Run Docker
   hosts: master_server
   become: yes
   tasks:
   - name: Install Docker
     apt:
       name: docker.io
       state: present

   - name: Start Docker service
     service:
       name: docker
       state: started
       enabled: yes

   - name: Install Docker Compose
     apt:
       name: docker-compose
       state: present

   - name: Install Docker Compose Plugin
     apt:
       name: docker-compose-plugin
       state: present
...
